#![feature(link_args)]

extern crate iota_bindings_rlib as bindings;
pub use bindings::*;

#[link_args = "-s EXPORTED_FUNCTIONS=[\
'_iota_ctrits_convert',\
'_iota_ctrits_ctrits_byte_length',\
'_iota_ctrits_ctrits_data',\
'_iota_ctrits_ctrits_encoding',\
'_iota_ctrits_ctrits_from_bytes',\
'_iota_ctrits_ctrits_from_trits',\
'_iota_ctrits_ctrits_from_trytes',\
'_iota_ctrits_ctrits_length',\
'_iota_ctrits_drop',\
'_iota_curl_bctrit_absorb',\
'_iota_curl_bctrit_delete',\
'_iota_curl_bctrit_new',\
'_iota_curl_bctrit_reset',\
'_iota_curl_bctrit_rounds',\
'_iota_curl_bctrit_set_rounds',\
'_iota_curl_bctrit_squeeze',\
'_iota_curl_trit_absorb',\
'_iota_curl_trit_delete',\
'_iota_curl_trit_new',\
'_iota_curl_trit_reset',\
'_iota_curl_trit_rounds',\
'_iota_curl_trit_set_rounds',\
'_iota_curl_trit_squeeze',\
'_iota_curl_trit_state',\
'_iota_kerl_trit_absorb',\
'_iota_kerl_trit_delete',\
'_iota_kerl_trit_new',\
'_iota_kerl_trit_reset',\
'_iota_kerl_trit_squeeze',\
'_iota_kerl_trit_state',\
'_iota_merkle_branch',\
'_iota_merkle_branch_drop',\
'_iota_merkle_branch_len',\
'_iota_merkle_count',\
'_iota_merkle_create',\
'_iota_merkle_depth',\
'_iota_merkle_drop',\
'_iota_merkle_root',\
'_iota_merkle_siblings',\
'_iota_merkle_size',\
'_iota_merkle_slice',\
'_iota_models_v1_bundle_hash',\
'_iota_models_v1_tx_address',\
'_iota_models_v1_tx_branch',\
'_iota_models_v1_tx_bundle',\
'_iota_models_v1_tx_current_index',\
'_iota_models_v1_tx_essence',\
'_iota_models_v1_tx_hash',\
'_iota_models_v1_tx_last_index',\
'_iota_models_v1_tx_nonce',\
'_iota_models_v1_tx_set_address',\
'_iota_models_v1_tx_set_branch',\
'_iota_models_v1_tx_set_bundle',\
'_iota_models_v1_tx_set_current_index',\
'_iota_models_v1_tx_set_last_index',\
'_iota_models_v1_tx_set_nonce',\
'_iota_models_v1_tx_set_signature_or_message',\
'_iota_models_v1_tx_set_tag',\
'_iota_models_v1_tx_set_timestamp',\
'_iota_models_v1_tx_set_trunk',\
'_iota_models_v1_tx_set_value',\
'_iota_models_v1_tx_signature_or_message',\
'_iota_models_v1_tx_tag',\
'_iota_models_v1_tx_timestamp',\
'_iota_models_v1_tx_trunk',\
'_iota_models_v1_tx_value',\
'_iota_models_v2_bundle_hash',\
'_iota_models_v2_tx_address',\
'_iota_models_v2_tx_attachment_timestamp',\
'_iota_models_v2_tx_attachment_timestamp_lower',\
'_iota_models_v2_tx_attachment_timestamp_upper',\
'_iota_models_v2_tx_branch',\
'_iota_models_v2_tx_bundle',\
'_iota_models_v2_tx_current_index',\
'_iota_models_v2_tx_essence',\
'_iota_models_v2_tx_hash',\
'_iota_models_v2_tx_last_index',\
'_iota_models_v2_tx_nonce',\
'_iota_models_v2_tx_obsolete_tag',\
'_iota_models_v2_tx_set_address',\
'_iota_models_v2_tx_set_attachment_timestamp',\
'_iota_models_v2_tx_set_attachment_timestamp_lower',\
'_iota_models_v2_tx_set_attachment_timestamp_upper',\
'_iota_models_v2_tx_set_branch',\
'_iota_models_v2_tx_set_bundle',\
'_iota_models_v2_tx_set_current_index',\
'_iota_models_v2_tx_set_last_index',\
'_iota_models_v2_tx_set_nonce',\
'_iota_models_v2_tx_set_obsolete_tag',\
'_iota_models_v2_tx_set_signature_or_message',\
'_iota_models_v2_tx_set_tag',\
'_iota_models_v2_tx_set_timestamp',\
'_iota_models_v2_tx_set_trunk',\
'_iota_models_v2_tx_set_value',\
'_iota_models_v2_tx_signature_or_message',\
'_iota_models_v2_tx_tag',\
'_iota_models_v2_tx_timestamp',\
'_iota_models_v2_tx_trunk',\
'_iota_models_v2_tx_value',\
'_iota_sign_checksum',\
'_iota_sign_checksum_validate',\
'_iota_sign_iss_address',\
'_iota_sign_iss_digest_bundle_signature',\
'_iota_sign_iss_digest_key',\
'_iota_sign_iss_key',\
'_iota_sign_iss_signature',\
'_iota_sign_iss_subseed',\
'_iota_sign_iss_subseed_to_signature',\
'_iota_mam_create',\
'_iota_mam_parse'\
]"]
extern "C" {}


fn main() {}
